### ISSUE TITLE
Can be D keywords escaped by additional prefix/suffix?

### ISSUE THREAD

**Issue by denizzzka** [msoucy/dproto#90]
Try to compile very common OSM .proto file same as described here: https://github.com/msoucy/dproto/issues/75#issue-144571686
```
/usr/include/dmd/phobos/std/exception.d(558,25): Error: uncaught CTFE exception object.Throwable("Reserved word: version")
/usr/include/dmd/phobos/std/exception.d(558,17):        thrown from here
../../.dub/packages/dproto-master/import/dproto/dproto.d(27,24):        called from here: ParseProtoSchema("osmformat.proto", "/** Copyright (c) 2010 Scott A. Crosby. <scott@sacrosby.com>\x0a\x0a   This program is free software: you can 
```

(Probably, associated with https://github.com/msoucy/dproto/issues/75)

**Comment by denizzzka** [comment]
Can be "version" word escaped by additional prefix/suffix or something like?

**Comment by msoucy** [comment]
So, an issue is that a pathological proto file would cause some issues like in #50 :

```proto
message Foo {
  required string version_ = 1;
  required string version = 2;
}
```

The consensus in #d was to have it error, though it's a good point that it would cause existing proto files to break. I'm really tempted to ignore the potential conflict, because honestly if someone's writing a file that convoluted they're kind of bringing it on themselves...

**Comment by denizzzka** [comment]
Suffix can be ajustable.

**Comment by denizzzka** [comment]
``option dproto_reserved_fmt`` isn't usable with ProtocolBuffer!(..) ?
